name: databricks deployment CI/CD 

on:
  push:
    branches:
      - main
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: development
    env:
      DATABRICKS_HOST: ${{secrets.DATABRICKS_URL}}
      DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}
      REPO_PATH: ${{secrets.DB_FOLDER_PATH}}

    steps:
      - name: Checkout Repos
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main
      
      - name: Extract Branch Name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/head/})"
        id: extract_branch

      - name: Update Databricks Git Folder
        run: |
          databricks repos update ${{env.REPO_PATH}} --branch "${{github.ref_name}}"




